name: Test on Gradle

on:
  [push, pull_request]

jobs:
  test-1-24-jdk25:

    runs-on: ubuntu-26.04

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK 26
        uses: actions/setup-java@v5
        with:
         java-version: '26'
         distribution: 'temurin'

      - name: Install GStreamer
        run: sudo apt-get update && sudo apt-get install gstreamer1.0-plugins-good gstreamer1.0-plugins-bad

      - name: Build with Gradle
        run: ./gradlew build

  test-1-20-jdk17:

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
         java-version: '17'
         distribution: 'temurin'

      - name: Install GStreamer
        run: sudo apt-get update && sudo apt-get install gstreamer1.0-plugins-good gstreamer1.0-plugins-bad

      - name: Build with Gradle
        run: ./gradlew build
